### ISSUE TITLE
gitee同步功能

### ISSUE THREAD

**Issue by lizhuangs** [zWingz/picgo-plugin-github-plus#14]
早知道作者有空，我就不自己折腾了，之前用picgo-plugin-github-plus拿去改了个[gitee](https://github.com/lizhuangs/picgo-plugin-gitee-uploader)的。我给picgo发issue作者没空，我只好自己弄了。不过貌似目前gitee同步功能还没有做。

**Comment by zWingz** [comment]
已经有了啊. 跟github一样的

**Comment by lizhuangs** [comment]
但是我用gitee上传，同步都报错。
```2019-06-20 11:47:32 [PicGo ERROR] HttpError: 404 Not Found
------Error Stack Begin------
HttpError: 404 Not Found
    at response.text.then.message (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------```

**Comment by zWingz** [comment]
检查你的`gitee`token是否正确, 还有`repo`

**Comment by lizhuangs** [comment]
感谢，是repo少了一个字母。。
