### ISSUE TITLE
无法删除图片

### ISSUE THREAD

**Issue by aldol-reaction** [zWingz/picgo-plugin-github-plus#30]
之前是可以正常删除和上传的，配置应该没有问题
2021-01-30 16:46:55 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 16:46:58 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 16:46:59 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:01:03 [PicGo INFO] Before transform 
2021-01-30 17:01:03 [PicGo INFO] Transforming... 
2021-01-30 17:01:03 [PicGo INFO] Before upload 
2021-01-30 17:01:03 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-30 17:01:17 [PicGo INFO] Uploading... 
2021-01-30 17:01:29 [PicGo SUCCESS] 
https://cdn.jsdelivr.net/gh/aldol-reaction/atom.img/img/test.png 
2021-01-30 17:01:46 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:01:48 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:01:51 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:01:56 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:01:58 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:02:00 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:02:02 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:02:09 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:04:19 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-01-30 17:04:27 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:04:38 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:04:39 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:04:45 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End------- 
2021-01-30 17:05:28 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Not Found
    at C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.onRemove (C:\Users\HuaWei\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:161:9)
-------Error Stack End-------

**Comment by aldol-reaction** [comment]
通过对配置文件里删除记录解决了
但是现在还是会时不时相册冒出来之前已经在仓库删除的图片

**Comment by aldol-reaction** [comment]
现在相册的问题有变成很多重复的图片（之前已经删除的）我已经崩溃了

**Comment by zWingz** [comment]
picgo的图片是所有插件共用的, 有可能是你其他插件上传了图片导致的
正常与github同步之后, 旧的图片不会再出现
能不能提供更相信信息?

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/109111279-9930f900-7773-11eb-85e4-231df9e04b9d.png)
这里看上传的源并不是github

**Comment by aldol-reaction** [comment]
我把其他插件禁用了，然后尝试上传同名照片。发现同名照片之前删除了，我再上传相同的名字不同照片的照片，会将过去删除了的照片上传而不是新的照片。现在已经正常了，谢谢
