### ISSUE TITLE
安装插件以后无法正确打开

### ISSUE THREAD

**Issue by wstZeng09** [zWingz/picgo-plugin-github-plus#46]
```
2022-02-09 15:57:37 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module '/Users/abcd/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus'
Require stack:
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/index.js
- /Applications/PicGo.app/Contents/Resources/app.asar/background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:125:24)
    at PluginLoader.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:78:26)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:40:43
    at Array.forEach (<anonymous>)
    at PluginHandler.install (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:39:29)
-------Error Stack End------- 
2022-02-09 15:57:37 [PicGo SUCCESS] 插件安装成功 



2022-02-09 15:19:25 [PicGo ERROR] startup error
------Error Stack Begin------
Error: Cannot find module '/Users/abcd/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:125:24)
    at Object.registerPluginShortKey (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:39170)
    at EventEmitter.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:41874)
-------Error Stack End-------
2022-02-09 15:19:25 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module '/Users/abcd/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:125:24)
    at PluginLoader.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:78:26)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:40:43
-------Error Stack End------- 
2022-02-09 15:19:25 [PicGo SUCCESS] 插件安装成功 


```

**Comment by zWingz** [comment]
>> Cannot find module '/Users/abcd/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/index.js'. Please verify that the package.json has a valid "main" entry

看样子是没正确安装好插件导致的, 试下重新安装或者是安装代理
