### ISSUE TITLE
PicGo2.3.0版本执行Sync origin或Pull origin操作失败报错

### ISSUE THREAD

**Issue by untir** [zWingz/picgo-plugin-github-plus#49]
![image](https://user-images.githubusercontent.com/25807071/154180694-ab8d4ac0-ce01-42a9-8bbd-7435fbf29318.png)

PicGo版本
![image](https://user-images.githubusercontent.com/25807071/154180584-ab220ecf-a2eb-4df1-961b-084ce8e2bb0d.png)

picgo.log
![image](https://user-images.githubusercontent.com/25807071/154180426-bf85f9cd-8ec9-4e01-bb45-c8eaabc0924a.png)

picgo.log
```nginx
2022-02-16 09:44:28 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: Cannot read property 'filter' of undefined
    at Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:32:28)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2022-02-16 09:44:34 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read property 'filter' of undefined
    at Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:89:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
```

**Comment by zWingz** [comment]
安装最新版本即可
